Run mkdir -p imgui
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

100 1380k    0 1380k    0     0  2169k      0 --:--:-- --:--:-- --:--:-- 2169k
100 1571k    0 1571k    0     0  2452k      0 --:--:-- --:--:-- --:--:-- 46.7M
cp: ./imgui.cpp and imgui.cpp are identical (not copied).
cp: ./imgui.h and imgui.h are identical (not copied).
cp: ./imgui_draw.cpp and imgui_draw.cpp are identical (not copied).
cp: ./imgui_tables.cpp and imgui_tables.cpp are identical (not copied).
cp: ./imgui_widgets.cpp and imgui_widgets.cpp are identical (not copied).
cp: ./imgui_demo.cpp and imgui_demo.cpp are identical (not copied).
Error: Process completed with exit code 1.
